### ISSUE TITLE
Do no remind on events that answered NO

### ISSUE THREAD

**Issue by vadimtk** [quarck/CalendarNotification#235] opened 2017-06-14 00:04 UTC
Can you make an option to disable notification on events that I answered NO ?

**Comment by quarck** [comment] 2017-06-14 05:00
Duplicate of #218. This functionality is not in the release yet, but that issue page has a link to a alpha build that has this functionality if you want to try it earlier.

**Closed by quarck** 2017-06-14 05:00 UTC
