### ISSUE TITLE
Issue/Bug: When snoozing from the notification bar, the launcher is called instead of reverting back to the last open app.

### ISSUE THREAD

**Issue by Tangram11** [quarck/CalendarNotification#18] opened 2016-04-05 07:35 UTC
This occurs on the Samsung S7. Action to reproduce:

1. User is in an app e.g. Gmail or Chrome.
2. Alert fires and is listed in the notification bar.
3. Notification bar is pulled down.
4. Alert is swiped down to expose "Snooze" option.
5. Snooze is selected
6. Snooze page appears and user selects e.g. 15 mins.
7. Snooze page closes and the user is taken to the home screen instead of back to the app that was being viewed when the alert fired.
8. To return to the last state prior to the alert firing, the user presses the Recent Apps key and taps the most recent app.

**Comment by quarck** [comment] 2016-04-19 22:10
Some improvements for this were added in f64cf243f409f898307ca01e18fd6cb4cd3b9785, not a full fix yet

**Comment by quarck** [comment] 2016-05-12 05:51
I've spend quite a while researching ways how to fix this problem. It seems to be a limitation of android itself, so unlikely it can be done, all activities started from notification are behaving the same way.

In the documentation about notifications & navigation Google is always mentioning "return home" rather than "return to previous app activity": 
http://developer.android.com/guide/topics/ui/notifiers/notifications.html#NotificationResponse

So would close as wontfix for now. If someone can point me to an example of the app that can do similar trick - it would be a great help.

**Comment by quarck** [comment] 2016-05-22 08:57
> The old Calendar Snooze (https://play.google.com/store/apps/details?id=com.bitfire.development.calendarsnooze) used to behave as required, but I think the way the Calendar Snooze reminder worked was more like an app forcing its way into the foreground, so when you snoozed or dismissed, it just closed and hence the previous app remained.

> It's not a big deal given how good CalendarNotification is now a few of the early bugs have been removed.

**Comment by quarck** [comment] 2016-06-13 16:07
It looks like that implementing this would be conflicting with #3. 
With old Calendar Snooze app, snooze dialog stays in the task switcher after event was snoozed. For Calendar Notifications Plus users have requested that Snooze dialog should disappear completely after event was snoozed, so to get event completely out of sight. To implement this behavior, Snooze dialog (activity) has special flag "no task history", which probably causing behavior described in #18. 
So it is either one or another. 

Alternative solution - is to not use Intents, but use low-level overlay to draw on top of current window without actually creating any new activities. This would require quite a lot of work and might be not very reliable, as well as would require some "suspicious" permissions - users might dislike it. 

Another possibility - create two Snooze Activities (they could derive from the same base class, so 99% of code would be shared), one with "no task history" flag and another without, Depending on user preferences he could have either #3 or #18 (this) working.

**Comment by quarck** [comment] 2016-06-15 04:49
Update: did a little bit of de-compiling of Calendar Snooze, it seems to be using all standard ways for creating activities, so nothing special on it side, no special flags, just pure "Android 1.6" depricated API. So it is very probable that behavior of Calendar Notifications Plus is caused by the fact that Snooze activity is hidden from "recents".

**Comment by quarck** [comment] 2016-06-15 05:22
Adding 

```
        intent.action = Intent.ACTION_MAIN;
        intent.addCategory(Intent.CATEGORY_LAUNCHER);

```

did the trick

**Closed by quarck** 2016-06-15 05:22 UTC
Labels: bug, help wanted
