### ISSUE TITLE
Issue/Bug: 8 or more active alarms makes looping alarm noise and default alarm tone

### ISSUE THREAD

**Issue by Tangram11** [quarck/CalendarNotification#24] opened 2016-04-23 04:11 UTC
**Phone**: Samsung S7

**Situation to reproduce**:
1. Set alarm tone to something not default (in my case a "click" sounding tone)
2. Set 8 or 9 events, 1 minute apart, and let them all fire without touching them

**Observe:**
- As the alarms fire, the first 7 will sound with the set tone (e.g. the "click").
- When then 8th tone sounds, it seems to use a default tone - a chime sound.
- If the screen is active when the 8th or 9th alarm is firing, it gets stuck in a loop and the chime keeps going unless either the screen is turned off or the user can snooze or clear a couple of them.

**Comment by quarck** [comment] 2016-04-23 17:11
Thank you for reporting, will take a look at this issue in a while

**Comment by quarck** [comment] 2016-05-08 17:51
This should be fixed in 2e269ce, would be available in the build 1.0.23. 

I wasn't able to reproduce issue with looping, but I can see what could be the cause, so fix is implemented.

**Comment by quarck** [comment] 2016-05-12 05:15
Please reopen if this is still an issue, closing for now

**Comment by quarck** [comment] 2016-05-20 23:17
Now this should be closed!

**Closed by quarck** 2016-05-20 23:17 UTC

**Comment by Tangram11** [comment] 2016-05-21 07:22
I confirm that after the last round of fixes, looping was fixed and the "chime" that was unexpectedly occurring was fixed with it. Great work, thanks!

**Comment by quarck** [comment] 2016-05-22 07:38
Thanks for confirming, actually I found another way to reproduce similar issue. When there are more than  8 reminders are snoozed until exactly same time, same issue might happen at snooze time. But this is now also fixed.

**Comment by quarck** [comment] 2016-05-22 07:54
New UI would be looking like this: 

[https://i.imgur.com/8At636L.png](https://i.imgur.com/8At636L.png)
