### ISSUE TITLE
notifications are not forwarded via pushbullet

### ISSUE THREAD

**Issue by TobiFfm** [quarck/CalendarNotification#284] opened 2018-08-13 14:56 UTC
a strange issue:
on my old android 6 / Sony Xperia Z3 each notification was forwarded via pushbullet to my pc.
with my new android 8.0 / S9 this isn't working anymore.
the normal calendar notifications (from the google calendar app) are forwarded. but unfortunately not the notifications from your app.

in pushbullet your app is activated for forwarding.

do i have to change someting in the notification-settings? anyone else with this issue?

**Comment by quarck** [comment] 2018-08-13 15:44
Disable "ongoing" notificatoins (settings -> notifications ->behavior). Usually apps like pushbullet and similar would ignore any ongoing notifications. 
Anyway - this is not a bug of this app, so closing it for now.

**Closed by quarck** 2018-08-13 15:44 UTC

**Comment by TobiFfm** [comment] 2018-08-13 17:15
Hmm, i cannot find >Disable "ongoing" notificatoins<
There's no such setting in the app

**Comment by TobiFfm** [comment] 2018-08-13 17:25
What option?

**Comment by quarck** [comment] 2018-08-13 17:31
Ah, sorry. I've replied via email and that didn't keep the attainment. One moment

**Comment by quarck** [comment] 2018-08-13 17:33
https://imgur.com/a/PSewpd9

**Comment by TobiFfm** [comment] 2018-08-13 17:46
i checked that option. no effect.
But i tried the group-option (as seen on your screenshot).
With that option checked the pushing works (also when ongoing is enabled).

unfortunately not exactly what i wanted. I would like to have a single notification pushed one after another to pushbullet. Now i have one notification with x events.
