### ISSUE TITLE
Problem with reminders

### ISSUE THREAD

**Issue by Kateylynn4** [quarck/CalendarNotification#313] opened 2019-04-09 17:30 UTC
I want reminders 15 minutes before, 10 minutes before, 5 minutes before, 1 minute before, and 0 minutes (or as close as I can get to it) a meeting starts. I tried using reminders but when I snooze the reminder, it shows a reminder 5 minutes later regardless of whether that matches up with my set reminders. So let's say I snooze a reminder 3 minutes before a meeting. I should get my next reminder 1 minute before. Instead the app reminds me 2 minutes after the meeting started because that is 5 minutes after I last snoozed.

I tried setting up these intervals in snooze but that didn't work either.

**Comment by quarck** [comment] 2019-04-09 21:55
Duplicate of #314

**Closed by quarck** 2019-04-09 21:55 UTC
